vich_uploader:
    db_driver: orm

    mappings:
      nomImage_image:
           uri_prefix: /images/nomImage_image
           upload_destination: '%kernel.project_dir%/public/images/nomImage_image'

      nomGallerie_image:
           uri_prefix: /images/nomGallerie_image
           upload_destination: '%kernel.project_dir%/public/images/nomGallerie_image'